apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat-deployment
  labels:
    app: nodegoat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodegoat-application
      app: nodegoat-app
  template:
    metadata:
      name: nodegoat-application
      labels:
        name: nodegoat-application
        app: nodegoat-app
    spec:
      containers:
        - name: nodegoat
          image: rbrayner/nodegoat:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: ""
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/nodegoat"
          command: [ "sh", "-c" ]
          args:
            - |
              until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && \
              node artifacts/db-reset.js && \
              npm start; do sleep 2; done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          securityContext:
            runAsUser: 999
          ports:
            - containerPort: 27017
