apiVersion: v1
kind: Service
metadata:
  name: nodegoat-web
  labels:
    app: nodegoat-app
spec:
  type: NodePort
  selector:
    app: nodegoat-app
    name: nodegoat-application
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30804
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
