name: 08-dast

on:
  pull_request:
  push:
    branches:
      - main

# Cancel previous runs if a new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dast-owasp-zap:
    name: DAST - OWASP ZAP
    runs-on: [arc-runner-set]
    timeout-minutes: 60
    permissions:
      contents: read
      security-events: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: ZAP Baseline Scan
        id: zap-scan
        continue-on-error: true
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://nodegoat-web.nodegoat'
          cmd_options: '-n owasp-zap.context -U admin -l WARN'
          fail_action: true
          allow_issue_writing: false
          artifact_name: 'zap-scan-report'

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            zap-scan-report.html
            zap-scan-report.md
            zap-scan-report.json

      - name: Fail if ZAP found issues
        if: steps.zap-scan.outcome == 'failure'
        run: exit 1